[package]
name = "serbo"
version = "0.1.0"
authors = ["Reed Krawiec <reedkrawiec@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"
rand = "0.7.3"
tungstenite = "0.11.0"